### ISSUE TITLE
ng add @datorama/akita not working

### ISSUE THREAD

**Issue by Teebo** [datorama/akita#776]
### Is this a regression?

Yes

### Description

The schematics folder is not present

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
Should work with v7.0.1

**Comment by Teebo** [comment]
@NetanelBasal thanks.
However, I am getting an error after the install and I cannot run any Akita schematics.

`An unhandled exception occurred: Cannot find module 'bluebird'`

**Comment by NetanelBasal** [comment]
Works for me:

![image](https://user-images.githubusercontent.com/6745730/143822146-120db4b2-7888-4548-8abf-6043599a4c27.png)
