### ISSUE TITLE
Type '0' cannot be used to index type

### ISSUE THREAD

**Issue by snebjorn** [datorama/akita#241]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
After updating from 3.16.0 to 4.1.0 I'm getting a lot of errors like this one

> ERROR in node_modules/@datorama/akita/src/entityStore.d.ts(44,31): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.

<details>
    <summary>All errors. Beware there's a lot!</summary>

```
> ng serve --aot

ERROR in node_modules/@datorama/akita/src/entityStore.d.ts(44,31): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/entityStore.d.ts(56,27): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/entityStore.d.ts(67,24): error TS2536: Type '0' cannot be used to index type 'S["ids"]'.
node_modules/@datorama/akita/src/entityStore.d.ts(67,77): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/entityStore.d.ts(71,24): error TS2536: Type '0' cannot be used to index type 'S["ids"]'.
node_modules/@datorama/akita/src/entityStore.d.ts(71,63): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/entityStore.d.ts(75,45): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/entityStore.d.ts(75,96): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/entityStore.d.ts(79,45): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/entityStore.d.ts(79,82): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/entityStore.d.ts(94,25): error TS2536: Type '0' cannot be used to index type 'S["ids"]'.
node_modules/@datorama/akita/src/entityStore.d.ts(94,57): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/entityStore.d.ts(94,77): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/entityStore.d.ts(94,116): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/entityStore.d.ts(94,136): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/entityStore.d.ts(109,26): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/entityStore.d.ts(123,41): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/entityStore.d.ts(134,25): error TS2536: Type '0' cannot be used to index type 'S["ids"]'.
node_modules/@datorama/akita/src/entityStore.d.ts(138,41): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/entityStore.d.ts(155,58): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/entityStore.d.ts(155,86): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/entityStore.d.ts(173,27): error TS2536: Type '0' cannot be used to index type 'S["ids"]'.
node_modules/@datorama/akita/src/entityStore.d.ts(182,30): error TS2536: Type '0' cannot be used to index type 'S["ids"]'.
node_modules/@datorama/akita/src/entityStore.d.ts(191,30): error TS2536: Type '0' cannot be used to index type 'S["ids"]'.
node_modules/@datorama/akita/src/entityStore.d.ts(217,38): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/entityStore.d.ts(217,78): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/entityStore.d.ts(217,98): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/entityStore.d.ts(218,43): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/entityStore.d.ts(218,63): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(50,42): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(50,81): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(51,42): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(51,73): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(52,42): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(52,81): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(53,42): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(53,73): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(54,42): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(54,73): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(55,29): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(78,39): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(78,67): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(79,39): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(79,59): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(80,39): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(80,67): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(81,39): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(81,59): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(82,39): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(82,59): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(83,15): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(92,24): error TS2536: Type '0' cannot be used to index type 'S["ids"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(92,51): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(93,24): error TS2536: Type '0' cannot be used to index type 'S["ids"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(93,57): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(105,25): error TS2536: Type '0' cannot be used to index type 'S["ids"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(105,50): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(106,34): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(106,56): error TS2536: Type '0' cannot be used to index type 'S["ids"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(106,94): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(107,25): error TS2536: Type '0' cannot be used to index type 'S["ids"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(107,56): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(108,46): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(108,77): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(116,19): error TS2536: Type '0' cannot be used to index type 'S["ids"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(116,33): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(141,63): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(141,96): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(142,40): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(150,46): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(150,67): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(159,38): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(168,35): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(178,33): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(179,37): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(189,34): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(190,38): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(215,19): error TS2536: Type '0' cannot be used to index type 'S["ids"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(216,19): error TS2536: Type '0' cannot be used to index type 'S["ids"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(217,33): error TS2536: Type '0' cannot be used to index type 'S["entities"]'.
node_modules/@datorama/akita/src/queryEntity.d.ts(228,20): error TS2536: Type '0' cannot be used to index type 'S["ids"]'.
node_modules/@datorama/akita/src/plugins/plugin.d.ts(17,67): error TS2536: Type '0' cannot be used to index type 'State["ids"]'.
node_modules/@datorama/akita/src/plugins/paginator/paginatorPlugin.d.ts(74,41): error TS2536: Type '0' cannot be used to index type 'State["entities"]'.
node_modules/@datorama/akita/src/plugins/paginator/paginatorPlugin.d.ts(79,19): error TS2536: Type '0' cannot be used to index type 'State["entities"]'.
node_modules/@datorama/akita/src/plugins/paginator/paginatorPlugin.d.ts(125,54): error TS2536: Type '0' cannot be used to index type 'State["entities"]'.
node_modules/@datorama/akita/src/plugins/paginator/paginatorPlugin.d.ts(125,109): error TS2536: Type '0' cannot be used to index type 'State["entities"]'.
node_modules/@datorama/akita/src/plugins/entityCollectionPlugin.d.ts(16,29): error TS2536: Type '0' cannot be used to index type 'State["ids"]'.
node_modules/@datorama/akita/src/plugins/entityCollectionPlugin.d.ts(17,73): error TS2536: Type '0' cannot be used to index type 'State["ids"]'.
node_modules/@datorama/akita/src/plugins/entityCollectionPlugin.d.ts(21,29): error TS2536: Type '0' cannot be used to index type 'State["ids"]'.
node_modules/@datorama/akita/src/plugins/entityCollectionPlugin.d.ts(25,29): error TS2536: Type '0' cannot be used to index type 'State["ids"]'.
node_modules/@datorama/akita/src/plugins/entityCollectionPlugin.d.ts(29,32): error TS2536: Type '0' cannot be used to index type 'State["ids"]'.
node_modules/@datorama/akita/src/plugins/entityCollectionPlugin.d.ts(33,32): error TS2536: Type '0' cannot be used to index type 'State["ids"]'.
node_modules/@datorama/akita/src/plugins/entityCollectionPlugin.d.ts(33,65): error TS2536: Type '0' cannot be used to index type 'State["ids"]'.
node_modules/@datorama/akita/src/plugins/entityCollectionPlugin.d.ts(37,25): error TS2536: Type '0' cannot be used to index type 'State["ids"]'.
node_modules/@datorama/akita/src/plugins/entityCollectionPlugin.d.ts(41,39): error TS2536: Type '0' cannot be used to index type 'State["ids"]'.
node_modules/@datorama/akita/src/plugins/entityCollectionPlugin.d.ts(49,27): error TS2536: Type '0' cannot be used to index type 'State["ids"]'.
node_modules/@datorama/akita/src/plugins/entityCollectionPlugin.d.ts(53,39): error TS2536: Type '0' cannot be used to index type 'State["ids"]'.
node_modules/@datorama/akita/src/plugins/entityCollectionPlugin.d.ts(57,30): error TS2536: Type '0' cannot be used to index type 'State["ids"]'.
node_modules/@datorama/akita/src/plugins/entityCollectionPlugin.d.ts(64,46): error TS2536: Type '0' cannot be used to index type 'State["ids"]'.
node_modules/@datorama/akita/src/plugins/entityCollectionPlugin.d.ts(68,27): error TS2536: Type '0' cannot be used to index type 'State["ids"]'.
node_modules/@datorama/akita/src/plugins/entityCollectionPlugin.d.ts(72,38): error TS2536: Type '0' cannot be used to index type 'State["ids"]'.
node_modules/@datorama/akita/src/plugins/stateHistory/entityStateHistoryPlugin.d.ts(10,57): error TS2536: Type '0' cannot be used to index type 'State["ids"]'.
node_modules/@datorama/akita/src/plugins/stateHistory/entityStateHistoryPlugin.d.ts(11,78): error TS2536: Type '0' cannot be used to index type 'State["ids"]'.
node_modules/@datorama/akita/src/plugins/stateHistory/entityStateHistoryPlugin.d.ts(12,24): error TS2536: Type '0' cannot be used to index type 'State["ids"]'.
node_modules/@datorama/akita/src/plugins/stateHistory/entityStateHistoryPlugin.d.ts(13,24): error TS2536: Type '0' cannot be used to index type 'State["ids"]'.
node_modules/@datorama/akita/src/plugins/stateHistory/entityStateHistoryPlugin.d.ts(14,17): error TS2536: Type '0' cannot be used to index type 'State["ids"]'.
node_modules/@datorama/akita/src/plugins/stateHistory/entityStateHistoryPlugin.d.ts(15,19): error TS2536: Type '0' cannot be used to index type 'State["ids"]'.
node_modules/@datorama/akita/src/plugins/stateHistory/entityStateHistoryPlugin.d.ts(16,31): error TS2536: Type '0' cannot be used to index type 'State["ids"]'.
node_modules/@datorama/akita/src/plugins/stateHistory/entityStateHistoryPlugin.d.ts(17,29): error TS2536: Type '0' cannot be used to index type 'State["ids"]'.
node_modules/@datorama/akita/src/plugins/stateHistory/entityStateHistoryPlugin.d.ts(18,25): error TS2536: Type '0' cannot be used to index type 'State["ids"]'.
node_modules/@datorama/akita/src/plugins/stateHistory/entityStateHistoryPlugin.d.ts(19,27): error TS2536: Type '0' cannot be used to index type 'State["ids"]'.
node_modules/@datorama/akita/src/plugins/stateHistory/entityStateHistoryPlugin.d.ts(20,30): error TS2536: Type '0' cannot be used to index type 'State["ids"]'.
node_modules/@datorama/akita/src/plugins/stateHistory/entityStateHistoryPlugin.d.ts(21,37): error TS2536: Type '0' cannot be used to index type 'State["ids"]'.
node_modules/@datorama/akita/src/plugins/dirtyCheck/entityDirtyCheckPlugin.d.ts(7,39): error TS2536: Type '0' cannot be used to index type 'State["entities"]'.
node_modules/@datorama/akita/src/plugins/dirtyCheck/entityDirtyCheckPlugin.d.ts(8,25): error TS2536: Type '0' cannot be used to index type 'State["ids"]'.
node_modules/@datorama/akita/src/plugins/dirtyCheck/entityDirtyCheckPlugin.d.ts(16,27): error TS2536: Type '0' cannot be used to index type 'State["ids"]'.
node_modules/@datorama/akita/src/plugins/dirtyCheck/entityDirtyCheckPlugin.d.ts(17,17): error TS2536: Type '0' cannot be used to index type 'State["ids"]'.
node_modules/@datorama/akita/src/plugins/dirtyCheck/entityDirtyCheckPlugin.d.ts(18,25): error TS2536: Type '0' cannot be used to index type 'State["ids"]'.
node_modules/@datorama/akita/src/plugins/dirtyCheck/entityDirtyCheckPlugin.d.ts(19,17): error TS2536: Type '0' cannot be used to index type 'State["ids"]'.
node_modules/@datorama/akita/src/plugins/dirtyCheck/entityDirtyCheckPlugin.d.ts(20,17): error TS2536: Type '0' cannot be used to index type 'State["ids"]'.
node_modules/@datorama/akita/src/plugins/dirtyCheck/entityDirtyCheckPlugin.d.ts(21,17): error TS2536: Type '0' cannot be used to index type 'State["ids"]'.
node_modules/@datorama/akita/src/plugins/dirtyCheck/entityDirtyCheckPlugin.d.ts(23,21): error TS2536: Type '0' cannot be used to index type 'State["ids"]'.
node_modules/@datorama/akita/src/plugins/dirtyCheck/entityDirtyCheckPlugin.d.ts(24,27): error TS2536: Type '0' cannot be used to index type 'State["ids"]'.
node_modules/@datorama/akita/src/plugins/dirtyCheck/entityDirtyCheckPlugin.d.ts(25,37): error TS2536: Type '0' cannot be used to index type 'State["ids"]'.
```

</details>

## Expected behavior
No errors

## Minimal reproduction of the problem with instructions

1. Update to `"@datorama/akita": "^4.1.0"`
2. Run `ng serve`
3. Watch it fail

## Environment

<pre><code>
Angular version: 8.0.2

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 8.0.4
Node: 12.4.0
OS: win32 x64
Angular: 8.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.4
@angular-devkit/build-angular     0.800.4
@angular-devkit/build-optimizer   0.800.4
@angular-devkit/build-webpack     0.800.4
@angular-devkit/core              8.0.4
@angular-devkit/schematics        7.3.9
@angular/cdk                      8.0.1
@angular/cli                      8.0.4
@angular/flex-layout              8.0.0-beta.26
@angular/material                 8.0.1
@ngtools/webpack                  8.0.4
@schematics/angular               8.0.4
@schematics/update                0.800.4
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0

For Tooling issues:
- Node version: 12.4.0
- Platform:  Windows
</code></pre>

**Comment by NetanelBasal** [comment]
It works fine on my machine.

![image](https://user-images.githubusercontent.com/6745730/60197015-302f0a80-9847-11e9-8565-8fa20f93f337.png)

Can you share the code? Reproduce it?

**Comment by NetanelBasal** [comment]
Try to clean your `node_modules` and install everything from scratch.

**Comment by snebjorn** [comment]
Issue persists after doing a "fresh" install

**Comment by NetanelBasal** [comment]
My TS version is `"typescript": "~3.4.3"`, try to use it.

**Comment by snebjorn** [comment]
Same issue with `"typescript": "~3.4.3"`

**Comment by GrandSchtroumpf** [comment]
Can you try to build (or serve with aot) ?

**Comment by snebjorn** [comment]
It might have something to do with `@datorama/akita-ng-router-store`

When I added it this stopped working https://stackblitz.com/edit/angular-ug2qht

**Comment by snebjorn** [comment]
> Can you try to build in prod (or serve with aot) ?

I tried with and without --aot they both fail

**Comment by snebjorn** [comment]
Found it!

I'm compiling in strict mode

**tsconfig.json**
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "esnext",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2015",
    "lib": ["es2018", "dom"],
    "types": ["jest"],
    "strict": true                     // strict mode
  }
}
```

**Comment by GrandSchtroumpf** [comment]
Hmmm, now the trick is to find which parameter of strict makes compilation fail...

**Comment by snebjorn** [comment]
> Hmmm, now the trick is to find which parameter of strict makes compilation fail...

"strictNullChecks": true

**Comment by NetanelBasal** [comment]
Should work with the latest version.

**Comment by snebjorn** [comment]
I can confirm that it works!
