### ISSUE TITLE
Types error

### ISSUE THREAD

**Issue by bogusweb** [datorama/akita#169]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
After update Akita from 1.24.3 to 2.1.2, ng serve throw types error.

## Minimal reproduction of the problem with instructions
error:
`error TS2339: Property 'id' does not exist on type 'TypeName | TypeName[]'.
  Property 'id' does not exist on type 'TypeName[]'.`
interface:
```
export interface TypeNameID {
  id: number;
}

export interface TypeName extends TypeNameID {
  name: string;
}
```

## Environment

<pre><code>
Angular version: 7.1.1

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
I can't see anything in your code that is related to Akita. 🤔

**Comment by bogusweb** [comment]
Hmm maybe, but only after update to 2.1.2 version, types throw error. After rollback to 1.24.2 everything is ok

**Comment by NetanelBasal** [comment]
You need to be more specific; I can't do anything with the code you show here. Also, did you update the Typescript version?

**Comment by bogusweb** [comment]
i create stackblitz for this: https://github-bteyx5.stackblitz.io (fork from issue link)

**Comment by NetanelBasal** [comment]
Why are you not reading the migrating guide or the docs? You need to add the `ActiveState` interface.

```ts
export interface TodosState extends EntityState<Todo>, ActiveState {
}

@Injectable({ providedIn: 'root' })
@StoreConfig({ name: 'todos' })
export class TodosStore extends EntityStore<TodosState, Todo> {

  constructor() {
    super({ 
      active: null
    });
  }

}
```
