### ISSUE TITLE
akita-ngdevtools throwing error on version 4.0.1

### ISSUE THREAD

**Issue by rosostolato** [datorama/akita#456]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
`ng build --prod` is throwing error with version 4.0.1

```
ERROR in src\app\app.module.ts(75,16): Error during template compile of 'AppModule'
  Function calls are not supported in decorators but 'InjectionToken' was called in 'DEVTOOLS_OPTIONS'
    'DEVTOOLS_OPTIONS' calls 'InjectionToken' at @datorama\akita-ngdevtools\datorama-akita-ngdevtools.ts(4,37).
```

Sorry, I couldn't test it on newer version of angular

**Comment by NetanelBasal** [comment]
@xbaun I'm wondering if the Nx upgrade causes this and issue #454.

**Comment by NetanelBasal** [comment]
Could you try 4.0.2, please?

**Comment by rosostolato** [comment]
It worked... but angular throwed some warnings

![image](https://user-images.githubusercontent.com/27731641/85064920-a75d5d00-b182-11ea-9629-ae7e074ae170.png)

**Comment by NetanelBasal** [comment]
What is your Angular version?

**Comment by xbaun** [comment]
@NetanelBasal I tested 4.0.1 and 4.0.2 and both worked with Angular 9.1.0 with `--prod` flag. What's the difference between this two versions?

**Comment by rosostolato** [comment]
> What is your Angular version?

I couldn't try in newer versions, just tried on my company's project that runs angular 7:

```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.3.9
Node: 11.12.0
OS: win32 x64
Angular: 7.2.16
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.4
@angular-devkit/build-angular     0.12.4
@angular-devkit/build-optimizer   0.12.4
@angular-devkit/build-webpack     0.12.4
@angular-devkit/core              7.2.4
@angular-devkit/schematics        7.3.9
@angular/cdk                      7.3.7
@angular/cli                      7.3.9
@angular/flex-layout              7.0.0-beta.24
@angular/material                 7.3.7
@ngtools/webpack                  7.2.4
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.28.4
```

**Comment by NetanelBasal** [comment]
This version supports v8+. I'll update the peer dependencies.
